/* Generated By:JJTree: Do not edit this line. ASTAttributeDefList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAttributeDefList extends SimpleNode {
  public ASTAttributeDefList(int id) {
    super(id);
  }

  public ASTAttributeDefList(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ef41f1d62d01477fbd6212407294bec (do not edit this line) */
