/* Generated By:JJTree: Do not edit this line. ASTAttributeDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAttributeDefinition extends SimpleNode {
  public ASTAttributeDefinition(int id) {
    super(id);
  }

  public ASTAttributeDefinition(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c77de6f833ecf689b3b872c4e44794e8 (do not edit this line) */
