/* Generated By:JJTree: Do not edit this line. ASTStreamFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTStreamFilter extends SimpleNode {
  public ASTStreamFilter(int id) {
    super(id);
  }

  public ASTStreamFilter(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53d80b60f11637242d6f51a2a6c02df7 (do not edit this line) */
