/* Generated By:JJTree: Do not edit this line. ASTWindowFrame.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWindowFrame extends SimpleNode {
  public ASTWindowFrame(int id) {
    super(id);
  }

  public ASTWindowFrame(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d23489a4887063f350fe0c3f6e8c8cc5 (do not edit this line) */
