/* Generated By:JJTree&JavaCC: Do not edit this line. EsperdentParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EsperdentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 7;
  /** RegularExpression Id. */
  int SCHEMA = 8;
  /** RegularExpression Id. */
  int STREAM = 9;
  /** RegularExpression Id. */
  int SOURCE = 10;
  /** RegularExpression Id. */
  int INSERT = 11;
  /** RegularExpression Id. */
  int INTO = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int WHERE = 15;
  /** RegularExpression Id. */
  int AS = 16;
  /** RegularExpression Id. */
  int WINDOW = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int WIN_LENGTH = 22;
  /** RegularExpression Id. */
  int WIN_TIME = 23;
  /** RegularExpression Id. */
  int WIN_TIME_BATCH = 24;
  /** RegularExpression Id. */
  int ROWS = 25;
  /** RegularExpression Id. */
  int RANGE = 26;
  /** RegularExpression Id. */
  int SLIDE = 27;
  /** RegularExpression Id. */
  int UNBOUNDED = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int FLOAT = 30;
  /** RegularExpression Id. */
  int TIMESTAMP = 31;
  /** RegularExpression Id. */
  int SECONDS = 32;
  /** RegularExpression Id. */
  int MINUTES = 33;
  /** RegularExpression Id. */
  int HOURS = 34;
  /** RegularExpression Id. */
  int DAYS = 35;
  /** RegularExpression Id. */
  int STRING = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 40;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 41;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 42;
  /** RegularExpression Id. */
  int EXPONENT = 43;
  /** RegularExpression Id. */
  int EQ = 44;
  /** RegularExpression Id. */
  int GT = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"create\"",
    "\"schema\"",
    "\"stream\"",
    "\"source\"",
    "\"insert\"",
    "\"into\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"as\"",
    "\"window\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\",\"",
    "\"win:length\"",
    "\"win:time\"",
    "\"win:time_batch\"",
    "\"rows\"",
    "\"range\"",
    "\"slide\"",
    "\"unbounded\"",
    "\"int\"",
    "\"float\"",
    "\"timestamp\"",
    "<SECONDS>",
    "<MINUTES>",
    "<HOURS>",
    "<DAYS>",
    "<STRING>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"=\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
  };

}
