/* Generated By:JavaCC: Do not edit this line. EsperdentParserTreeConstants.java Version 5.0 */
package parser;

public interface EsperdentParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCREATECLAUSE = 2;
  public int JJTATTRIBUTEDEFLIST = 3;
  public int JJTATTRIBUTEDEFINITION = 4;
  public int JJTATTRIBUTETYPE = 5;
  public int JJTSOURCE = 6;
  public int JJTINSERTCLAUSE = 7;
  public int JJTQUERY = 8;
  public int JJTSELECTCLAUSE = 9;
  public int JJTSELECTLIST = 10;
  public int JJTATTRIBUTE = 11;
  public int JJTFROMCLAUSE = 12;
  public int JJTFROMLIST = 13;
  public int JJTSTREAM = 14;
  public int JJTSTREAMFILTER = 15;
  public int JJTWINDOWSPEC = 16;
  public int JJTWINDOWFRAME = 17;
  public int JJTWINDOWFRAMEUNITS = 18;
  public int JJTWINDOWFRAMESTART = 19;
  public int JJTVALUESPEC = 20;
  public int JJTUNITS = 21;
  public int JJTSLIDECLAUSE = 22;
  public int JJTWHERECLAUSE = 23;
  public int JJTCONDAND = 24;
  public int JJTCONDOR = 25;
  public int JJTCONDEQ = 26;
  public int JJTCONDGT = 27;
  public int JJTSTRING = 28;
  public int JJTINTEGER = 29;
  public int JJTFLOAT = 30;
  public int JJTNAME = 31;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CreateClause",
    "AttributeDefList",
    "AttributeDefinition",
    "AttributeType",
    "Source",
    "InsertClause",
    "Query",
    "SelectClause",
    "SelectList",
    "Attribute",
    "FromClause",
    "FromList",
    "Stream",
    "StreamFilter",
    "WindowSpec",
    "WindowFrame",
    "WindowFrameUnits",
    "WindowFrameStart",
    "ValueSpec",
    "Units",
    "SlideClause",
    "WhereClause",
    "CondAnd",
    "CondOr",
    "CondEq",
    "CondGt",
    "String",
    "Integer",
    "Float",
    "Name",
  };
}
/* JavaCC - OriginalChecksum=c07dfc09f41c4476dfc25fe2eda41f55 (do not edit this line) */
