/* Generated By:JJTree: Do not edit this line. ASTInsertClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTInsertClause extends SimpleNode {
  public ASTInsertClause(int id) {
    super(id);
  }

  public ASTInsertClause(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=55425c3f68b3ce06f28ae36f53c8428e (do not edit this line) */
