/* Generated By:JJTree: Do not edit this line. ASTWindowSpec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWindowSpec extends SimpleNode {
  public ASTWindowSpec(int id) {
    super(id);
  }

  public ASTWindowSpec(EsperdentParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EsperdentParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cf0c2603a1e282b19726a8a8ee1cd82 (do not edit this line) */
