/* Generated By:JavaCC: Do not edit this line. EsperdentParserTreeConstants.java Version 5.0 */
package parser;

public interface EsperdentParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCREATECLAUSE = 2;
  public int JJTATTRIBUTEDEFLIST = 3;
  public int JJTATTRIBUTEDEFINITION = 4;
  public int JJTATTRIBUTETYPE = 5;
  public int JJTINSERTCLAUSE = 6;
  public int JJTQUERY = 7;
  public int JJTSELECTCLAUSE = 8;
  public int JJTSELECTLIST = 9;
  public int JJTATTRIBUTE = 10;
  public int JJTFROMCLAUSE = 11;
  public int JJTFROMLIST = 12;
  public int JJTSTREAM = 13;
  public int JJTWINDOWSPEC = 14;
  public int JJTWINDOWFRAME = 15;
  public int JJTWINDOWFRAMEUNITS = 16;
  public int JJTWINDOWFRAMESTART = 17;
  public int JJTUNITS = 18;
  public int JJTWHERECLAUSE = 19;
  public int JJTCONDAND = 20;
  public int JJTCONDOR = 21;
  public int JJTCONDEQ = 22;
  public int JJTCONDGT = 23;
  public int JJTNAME = 24;
  public int JJTINTEGER = 25;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "CreateClause",
    "AttributeDefList",
    "AttributeDefinition",
    "AttributeType",
    "InsertClause",
    "Query",
    "SelectClause",
    "SelectList",
    "Attribute",
    "FromClause",
    "FromList",
    "Stream",
    "WindowSpec",
    "WindowFrame",
    "WindowFrameUnits",
    "WindowFrameStart",
    "Units",
    "WhereClause",
    "CondAnd",
    "CondOr",
    "CondEq",
    "CondGt",
    "Name",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=02d01a0d96f2152984bd96120316d4d5 (do not edit this line) */
