/* Generated By:JavaCC: Do not edit this line. EsperdentParserVisitor.java Version 5.0 */
package parser;

public interface EsperdentParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTCreateClause node, Object data);
  public Object visit(ASTAttributeDefList node, Object data);
  public Object visit(ASTAttributeDefinition node, Object data);
  public Object visit(ASTAttributeType node, Object data);
  public Object visit(ASTInsertClause node, Object data);
  public Object visit(ASTQuery node, Object data);
  public Object visit(ASTSelectClause node, Object data);
  public Object visit(ASTSelectList node, Object data);
  public Object visit(ASTAttribute node, Object data);
  public Object visit(ASTFromClause node, Object data);
  public Object visit(ASTFromList node, Object data);
  public Object visit(ASTStream node, Object data);
  public Object visit(ASTWindowSpec node, Object data);
  public Object visit(ASTWindowFrame node, Object data);
  public Object visit(ASTWindowFrameUnits node, Object data);
  public Object visit(ASTWindowFrameStart node, Object data);
  public Object visit(ASTUnits node, Object data);
  public Object visit(ASTWhereClause node, Object data);
  public Object visit(ASTCondAnd node, Object data);
  public Object visit(ASTCondOr node, Object data);
  public Object visit(ASTCondEq node, Object data);
  public Object visit(ASTCondGt node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=73a2ac21f2d3aecc7480a7e2abdf31da (do not edit this line) */
