/* Generated By:JJTree&JavaCC: Do not edit this line. EsperdentParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EsperdentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 7;
  /** RegularExpression Id. */
  int SCHEMA = 8;
  /** RegularExpression Id. */
  int STREAM = 9;
  /** RegularExpression Id. */
  int INSERT = 10;
  /** RegularExpression Id. */
  int INTO = 11;
  /** RegularExpression Id. */
  int SELECT = 12;
  /** RegularExpression Id. */
  int FROM = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int AS = 15;
  /** RegularExpression Id. */
  int WINDOW = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int WIN_LENGTH = 21;
  /** RegularExpression Id. */
  int WIN_TIME = 22;
  /** RegularExpression Id. */
  int WIN_TIME_BATCH = 23;
  /** RegularExpression Id. */
  int ROWS = 24;
  /** RegularExpression Id. */
  int RANGE = 25;
  /** RegularExpression Id. */
  int INT = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int TIMESTAMP = 28;
  /** RegularExpression Id. */
  int SECONDS = 29;
  /** RegularExpression Id. */
  int MINUTES = 30;
  /** RegularExpression Id. */
  int HOURS = 31;
  /** RegularExpression Id. */
  int DAYS = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 37;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 38;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 39;
  /** RegularExpression Id. */
  int EXPONENT = 40;
  /** RegularExpression Id. */
  int EQ = 41;
  /** RegularExpression Id. */
  int GT = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"create\"",
    "\"schema\"",
    "\"stream\"",
    "\"insert\"",
    "\"into\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"as\"",
    "\"window\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\",\"",
    "\"win:length\"",
    "\"win:time\"",
    "\"win:time_batch\"",
    "\"rows\"",
    "\"range\"",
    "\"int\"",
    "\"float\"",
    "\"timestamp\"",
    "<SECONDS>",
    "<MINUTES>",
    "<HOURS>",
    "<DAYS>",
    "<STRING>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\"=\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"*\"",
    "\".\"",
  };

}
